# Generated by Django 5.2.5 on 2025-09-10 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salespartner',
            name='owner_name',
        ),
    ]
