# Generated by Django 5.2.5 on 2025-09-12 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_remove_salespartner_owner_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='매입처명')),
                ('biz_no', models.CharField(blank=True, max_length=50, verbose_name='사업자번호')),
                ('fax', models.CharField(blank=True, max_length=50, verbose_name='팩스번호')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='주소')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='대표 이메일')),
            ],
            options={
                'verbose_name': '매입처',
                'verbose_name_plural': '매입처 목록',
                'db_table': 'partners_purchasepartner',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchasePartnerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='담당자명')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='부서')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='연락처')),
                ('extension', models.CharField(blank=True, max_length=20, verbose_name='내선')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='이메일')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='partners.purchasepartner')),
            ],
            options={
                'verbose_name': '매입처 담당자',
                'verbose_name_plural': '매입처 담당자 목록',
                'db_table': 'partners_purchasepartner_contact',
                'ordering': ['id'],
            },
        ),
    ]
