# Generated by Django 5.2.5 on 2025-09-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_purchasepartner_purchasepartnercontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasepartner',
            name='homepage',
            field=models.URLField(blank=True, null=True, verbose_name='홈페이지'),
        ),
    ]
