# Generated by Django 5.2.5 on 2025-09-29 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='무제 계약', max_length=200)),
                ('customer_company', models.CharField(blank=True, max_length=200)),
                ('customer_manager', models.CharField(blank=True, max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=50)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('ship_item', models.CharField(blank=True, max_length=200)),
                ('ship_date', models.DateField(blank=True, null=True)),
                ('ship_addr', models.CharField(blank=True, max_length=300)),
                ('ship_phone', models.CharField(blank=True, max_length=50)),
                ('collect_invoice_date', models.DateField(blank=True, null=True)),
                ('collect_date', models.DateField(blank=True, null=True)),
                ('collect_note', models.TextField(blank=True)),
                ('special_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', '임시저장'), ('submitted', '결재요청'), ('processing', '결재처리중'), ('completed', '결재완료')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract_no', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('year', models.PositiveIntegerField(blank=True, db_index=True, editable=False, null=True)),
                ('seq', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('sales_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_owned', to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts_written', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContractImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ImageField(upload_to='contracts/orig/%Y/%m/%d/')),
                ('thumb', models.ImageField(blank=True, upload_to='contracts/thumb/%Y/%m/%d/')),
                ('medium', models.ImageField(blank=True, upload_to='contracts/medium/%Y/%m/%d/')),
                ('filename', models.CharField(blank=True, db_index=True, max_length=255)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='expenses.contract')),
            ],
        ),
        migrations.CreateModel(
            name='ContractItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('qty', models.PositiveIntegerField(default=0)),
                ('spec', models.CharField(blank=True, max_length=100)),
                ('sell_unit', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('sell_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('buy_unit', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('buy_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('vat_mode', models.CharField(choices=[('separate', 'VAT별도'), ('included', 'VAT포함'), ('exempt', '면세')], default='separate', max_length=10)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='expenses.contract')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('handler', models.CharField(blank=True, max_length=50)),
                ('vat_rate', models.IntegerField(choices=[(0, '0%'), (10, '10%')], default=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100, verbose_name='품목')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='수량')),
                ('unit_price', models.PositiveIntegerField(default=0, verbose_name='매입단가')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='expenses.expensereport')),
            ],
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(fields=('year', 'seq'), name='uniq_contract_year_seq'),
        ),
        migrations.AddIndex(
            model_name='contractimage',
            index=models.Index(fields=['contract', 'uploaded_at'], name='expenses_co_contrac_17bde4_idx'),
        ),
    ]
