# Generated by Django 5.2.5 on 2025-09-02 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='무제 계약', max_length=200)),
                ('customer_company', models.CharField(blank=True, max_length=200)),
                ('customer_manager', models.CharField(blank=True, max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=50)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('ship_item', models.CharField(blank=True, max_length=200)),
                ('ship_date', models.DateField(blank=True, null=True)),
                ('ship_addr', models.CharField(blank=True, max_length=300)),
                ('ship_phone', models.CharField(blank=True, max_length=50)),
                ('collect_invoice_date', models.DateField(blank=True, null=True)),
                ('collect_date', models.DateField(blank=True, null=True)),
                ('collect_note', models.CharField(blank=True, max_length=500)),
                ('special_note', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('draft', '임시저장'), ('submitted', '품의요청'), ('approved', '승인'), ('rejected', '반려')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_owned', to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts_written', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ImageField(upload_to='contracts/orig/%Y/%m/%d/')),
                ('thumb', models.ImageField(blank=True, upload_to='contracts/thumb/%Y/%m/%d/')),
                ('medium', models.ImageField(blank=True, upload_to='contracts/medium/%Y/%m/%d/')),
                ('filename', models.CharField(blank=True, db_index=True, max_length=255)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='expenses.contract')),
            ],
            options={
                'indexes': [models.Index(fields=['contract', 'uploaded_at'], name='expenses_co_contrac_17bde4_idx')],
            },
        ),
    ]
