# Generated by Django 5.2.5 on 2025-09-05 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_contract_contractimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', '임시저장'), ('submitted', '품의요청'), ('processing', '결재처리중'), ('completed', '결재완료')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='ContractItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('qty', models.PositiveIntegerField(default=0)),
                ('spec', models.CharField(blank=True, max_length=100)),
                ('sell_unit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sell_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('buy_unit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('buy_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('vat_mode', models.CharField(choices=[('separate', 'VAT별도'), ('included', 'VAT포함'), ('exempt', '면세')], default='separate', max_length=10)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='expenses.contract')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
