# Generated by Django 5.2.5 on 2025-09-17 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_contract_status_contractitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractitem',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='expenses.contract'),
        ),
    ]
