# Generated by Django 5.2.5 on 2025-09-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_alter_contract_options_remove_contract_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='collect_note',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='contract',
            name='special_note',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
