# Generated by Django 5.2.5 on 2025-09-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_contract_collect_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractitem',
            name='buy_unit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='contractitem',
            name='sell_unit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
    ]
