# Generated by Django 5.2.5 on 2025-09-29 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('대표이사', '대표이사'), ('실장', '실장'), ('상무', '상무'), ('부장', '부장'), ('과장', '과장'), ('대리', '대리'), ('주임', '주임'), ('사원', '사원'), ('차장', '차장')], max_length=20)),
                ('department', models.CharField(choices=[('연구개발전담부(디자인팀)', '연구개발전담부(디자인팀)'), ('MD팀(제품기획및개발)', 'MD팀(제품기획및개발)'), ('영업팀', '영업팀'), ('회계팀', '회계팀'), ('물류팀', '물류팀')], max_length=20)),
                ('access', models.CharField(choices=[('관리자모드', '관리자모드'), ('사장모드', '사장모드'), ('실장모드', '실장모드'), ('직원모드', '직원모드')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
