# Generated by Django 5.2.5 on 2025-08-22 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('사장', '사장'), ('부장', '부장'), ('팀장', '팀장')], max_length=20)),
                ('department', models.CharField(choices=[('홍보팀', '홍보팀'), ('기획팀', '기획팀'), ('회장단', '회장단')], max_length=20)),
                ('access', models.CharField(choices=[('관리자모드', '관리자모드'), ('사장모드', '사장모드'), ('직원모드', '직원모드')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
