# Generated by Django 5.2.5 on 2025-09-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access',
            field=models.CharField(choices=[('관리자모드', '관리자모드'), ('사장모드', '사장모드'), ('직원모드', '직원모드'), ('실장모드', '실장모드')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('연구개발전담부(디자인팀)', '연구개발전담부(디자인팀)'), ('MD팀(제품기획및개발)', 'MD팀(제품기획및개발)'), ('영업팀', '영업팀'), ('회계팀', '회계팀'), ('물류팀', '물류팀')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('대표이사', '대표이사'), ('실장', '실장'), ('부장', '부장'), ('과장', '과장'), ('대리', '대리'), ('주임', '주임'), ('사원', '사원'), ('차장', '차장')], max_length=20),
        ),
    ]
