# Generated by Django 5.2.5 on 2025-09-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_access_alter_profile_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access',
            field=models.CharField(choices=[('관리자모드', '관리자모드'), ('사장모드', '사장모드'), ('실장모드', '실장모드'), ('직원모드', '직원모드')], max_length=20),
        ),
    ]
