# Generated by Django 5.2.5 on 2025-09-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('대표이사', '대표이사'), ('실장', '실장'), ('상무', '상무'), ('부장', '부장'), ('과장', '과장'), ('대리', '대리'), ('주임', '주임'), ('사원', '사원'), ('차장', '차장')], max_length=20),
        ),
    ]
